server:
  shutdown: graceful
management:
  endpoint:
    health:
      probes:
        enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
spring:
  autoconfigure:
    exclude:
  data:
    redis:
      host: redis_1
  lifecycle:
    timeout-per-shutdown-phase: 1m
  datasource:
    url: jdbc:mariadb://mariadb_1:3306/mbooks__prod?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul
    username: root
    password: uoise9999
  jpa:
    properties:
      hibernate:
        show_sql: false
        format_sql: false
        use_sql_comments: false
    hibernate:
      ddl-auto: update
logging:
  level:
    root: INFO
    com.ll.mbooks: INFO
    org.hibernate.orm.jdbc.bind: INFO
    org.hibernate.orm.jdbc.extract: INFO
custom:
  site:
    baseUrl: "https://service-domain"